"""Watch-before-edit: analyze a video once, write analysis.json that the whole
pipeline (highlights, b-roll, captions, QA) consumes.

Analysis: duration, resolution, fps, scene cuts, per-window audio energy,
silence map, speech/silence ratio estimate.
"""

import json
import os
import subprocess

from video import ffmpeg as vff

ANALYSIS_FILE = "analysis.json"


def _run(argv):
    proc = subprocess.run(argv, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg analysis failed: {proc.stderr.strip()[-400:]}")
    return proc.stderr


def scene_cuts(input_path, threshold=0.4):
    """Return [seconds] where scene cuts were detected."""
    err = _run(["ffmpeg", "-hide_banner", "-i", input_path, "-vf",
                f"select='gt(scene,{threshold})',showinfo", "-f", "null", "-"])
    cuts = []
    for line in err.splitlines():
        if "showinfo" in line and "pts_time:" in line:
            try:
                t = line.split("pts_time:")[1].split()[0]
                cuts.append(round(float(t), 2))
            except (ValueError, IndexError):
                pass
    return cuts


def silence_map(input_path, noise_db=-30, min_dur=0.5):
    """Return [(start, end)] silent regions via silencedetect."""
    err = _run(["ffmpeg", "-hide_banner", "-i", input_path, "-af",
                f"silencedetect=noise={noise_db}dB:d={min_dur}", "-f", "null", "-"])
    spans, start = [], None
    for line in err.splitlines():
        if "silence_start" in line:
            try:
                start = float(line.split("silence_start:")[1].strip())
            except ValueError:
                start = None
        elif "silence_end" in line and start is not None:
            try:
                end = float(line.split("silence_end:")[1].split("|")[0].strip())
                spans.append((round(start, 2), round(end, 2)))
            except ValueError:
                pass
            start = None
    return spans


def energy_curve(input_path, window_s=1.0):
    """Per-window mean audio energy (0..1-ish) via astats metadata."""
    info = vff.info(input_path)
    dur = info.get("duration", 0)
    if dur <= 0:
        return []
    # Use volumedetect per chunk is slow; instead use ebur128 momentary
    # loudness. NOTE: framelog lines only appear with -v verbose.
    err = _run(["ffmpeg", "-hide_banner", "-v", "verbose", "-i", input_path,
                "-map", "0:a", "-af", "ebur128=peak=true:framelog=verbose",
                "-f", "null", "-"])
    curve = []
    for line in err.splitlines():
        if "TARGET:" in line and " M:" in line:
            # "[Parsed_ebur128_0 @ ...] t: 0.1 TARGET:-23 LUFS M:-23.1 S:..."
            try:
                m = float(line.split(" M:")[1].split()[0])
                # map -60..0 dB LUFS to 0..1
                curve.append(round(max(0.0, min(1.0, (m + 60) / 60)), 3))
            except (ValueError, IndexError):
                pass
    # downsample to window_s buckets
    per_sec = 10  # ebur128 framelog ~10Hz when quiet? be defensive
    if not curve:
        return []
    bucket = max(1, int(window_s * per_sec))
    out = []
    for i in range(0, len(curve), bucket):
        seg = curve[i:i + bucket]
        out.append(round(sum(seg) / len(seg), 3))
    return out


def watch(input_path, out_dir=None):
    """Full analysis pass. Returns dict and writes analysis.json."""
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"input not found: {input_path!r}")
    if not vff.which_ffmpeg():
        raise RuntimeError("ffmpeg not found — see video/SETUP.md")
    info = vff.info(input_path)
    dur = info.get("duration", 0)
    cuts = scene_cuts(input_path)
    silence = silence_map(input_path)
    energy = energy_curve(input_path)
    silent_s = sum(e - s for s, e in silence)
    analysis = {
        "input": os.path.abspath(input_path),
        "duration": round(dur, 2),
        "width": info.get("width"), "height": info.get("height"),
        "fps": info.get("fps"), "vcodec": info.get("vcodec"),
        "has_audio": bool(info.get("acodec")),
        "scene_cuts": cuts,
        "scene_count": len(cuts),
        "silence_spans": silence,
        "silent_seconds": round(silent_s, 2),
        "speech_ratio": round(max(0.0, min(1.0, 1 - silent_s / dur)), 3) if dur else 0,
        "energy_curve": energy,
        "notes": "generated by editor watch — consume via highlights/broll/captions",
    }
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, ANALYSIS_FILE), "w", encoding="utf-8") as fh:
            json.dump(analysis, fh, indent=2)
    return analysis


def load(out_dir):
    p = os.path.join(out_dir, ANALYSIS_FILE)
    if not os.path.exists(p):
        raise FileNotFoundError(f"no analysis.json in {out_dir!r} — run `editor watch` first")
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)
